#include "../../content/config.h"
#ifdef AUDIO_WAVESABRE
#include "WaveSabre/WaveSabreCore/src/Adultery.cpp"
#include "WaveSabre/WaveSabreCore/src/AllPass.cpp"
#include "WaveSabre/WaveSabreCore/src/AllPassDelay.cpp"
#include "WaveSabre/WaveSabreCore/src/BiquadFilter.cpp"
#include "WaveSabre/WaveSabreCore/src/Cathedral.cpp"
#include "WaveSabre/WaveSabreCore/src/Chamber.cpp"
#include "WaveSabre/WaveSabreCore/src/Comb.cpp"
#include "WaveSabre/WaveSabreCore/src/Crusher.cpp"
#include "WaveSabre/WaveSabreCore/src/DelayBuffer.cpp"
#include "WaveSabre/WaveSabreCore/src/Device.cpp"
#include "WaveSabre/WaveSabreCore/src/Echo.cpp"
#include "WaveSabre/WaveSabreCore/src/Envelope.cpp"
#include "WaveSabre/WaveSabreCore/src/Falcon.cpp"
#include "WaveSabre/WaveSabreCore/src/GmDls.cpp"
#include "WaveSabre/WaveSabreCore/src/GsmSample.cpp"
#include "WaveSabre/WaveSabreCore/src/Helpers.cpp"
#include "WaveSabre/WaveSabreCore/src/Leveller.cpp"
#include "WaveSabre/WaveSabreCore/src/MxcsrFlagGuard.cpp"
#include "WaveSabre/WaveSabreCore/src/ResampleBuffer.cpp"
#include "WaveSabre/WaveSabreCore/src/SamplePlayer.cpp"
#include "WaveSabre/WaveSabreCore/src/Scissor.cpp"
#include "WaveSabre/WaveSabreCore/src/Slaughter.cpp"
#include "WaveSabre/WaveSabreCore/src/Smasher.cpp"
#include "WaveSabre/WaveSabreCore/src/Specimen.cpp"
#include "WaveSabre/WaveSabreCore/src/StateVariableFilter.cpp"
#include "WaveSabre/WaveSabreCore/src/SynthDevice.cpp"
#include "WaveSabre/WaveSabreCore/src/Twister.cpp"
#include "WaveSabre/WaveSabreCore/src/Deprecated/Thunder.cpp"

#include "WaveSabre/WaveSabrePlayerLib/src/CriticalSection.cpp"
#include "WaveSabre/WaveSabrePlayerLib/src/DirectSoundRenderThread.cpp"
#include "WaveSabre/WaveSabrePlayerLib/src/IPlayer.cpp"
// #include "WaveSabre/WaveSabrePlayerLib/src/PreRenderPlayer.cpp"
#include "WaveSabre/WaveSabrePlayerLib/src/RealtimePlayer.cpp"
#include "WaveSabre/WaveSabrePlayerLib/src/SongRenderer.cpp"
#include "WaveSabre/WaveSabrePlayerLib/src/SongRenderer.Track.cpp"
// #include "WaveSabre/WaveSabrePlayerLib/src/WavWriter.cpp"

const IID GUID_NULL;
#endif
